// lib/fallback-data.js
// Sample data used when Supabase is not yet configured.
// This allows the site to run immediately after `npm install && npm run dev`.
// Once Supabase is connected, all data comes from the CMS.

export const FALLBACK_CONTENT = {
  hero_title: "Building Solana's Future in Malaysia",
  hero_subtitle:
    'The home for Solana builders, creators, and innovators in Malaysia. Join the movement shaping Web3 in Southeast Asia.',
  stats_members: '150+',
  stats_events: '30+',
  stats_projects: '45+',
  stats_bounties: '80+',
  stats_reach: '5,000+',
  join_title: 'Ready to Build the Future?',
  join_subtitle:
    'Join Superteam Malaysia and connect with the most ambitious builders in the Solana ecosystem.',
  telegram_url: 'https://t.me/SuperteamMY',
  discord_url: 'https://discord.gg/superteammy',
  twitter_url: 'https://x.com/SuperteamMY',
  luma_url: 'https://lu.ma/superteammy',
};

export const FALLBACK_EVENTS = [
  {
    id: '1',
    title: 'Solana Hacker House KL',
    date: '2026-03-15',
    time: '10:00',
    location: 'MAHSA Avenue, Kuala Lumpur',
    type: 'hackathon',
    status: 'upcoming',
    description:
      'A 2-day builder sprint for Solana developers in Malaysia. Build, collaborate, and ship.',
    luma_url: 'https://lu.ma/superteammy',
    featured: true,
  },
  {
    id: '2',
    title: 'Web3 Builder Meetup #12',
    date: '2026-03-22',
    time: '19:00',
    location: 'Co-labs Starling, PJ',
    type: 'meetup',
    status: 'upcoming',
    description: 'Monthly community gathering for Solana builders.',
    luma_url: 'https://lu.ma/superteammy',
    featured: false,
  },
  {
    id: '3',
    title: 'Solana Workshop: Anchor 101',
    date: '2026-04-05',
    time: '14:00',
    location: 'Google for Startups KL',
    type: 'workshop',
    status: 'upcoming',
    description: 'Hands-on workshop building your first Anchor program.',
    luma_url: 'https://lu.ma/superteammy',
    featured: false,
  },
  {
    id: '4',
    title: 'Superteam Demo Day',
    date: '2026-02-10',
    time: '14:00',
    location: 'Impact Hub KL',
    type: 'demo',
    status: 'past',
    description: 'Builders showcased their Solana projects to investors and the community.',
    luma_url: '',
    featured: false,
  },
  {
    id: '5',
    title: 'Solana Breakpoint Watchparty',
    date: '2026-01-20',
    time: '20:00',
    location: 'WeWork Equatorial Plaza',
    type: 'meetup',
    status: 'past',
    description: "Community watchparty for Solana's biggest conference of the year.",
    luma_url: '',
    featured: false,
  },
];

export const FALLBACK_MEMBERS = [
  {
    id: '1',
    name: 'Ahmad Rizal',
    role: 'Lead Rust Developer',
    company: 'SolanaLabs MY',
    skills: ['Rust', 'Frontend'],
    twitter: 'ahmadrizal',
    badge: 'Core Contributor',
    bio: 'Building DeFi infrastructure on Solana since 2022.',
    achievements: { hackathon_wins: 3, projects_built: 5, grants_received: 2, bounties_completed: 12 },
    featured: true,
  },
  {
    id: '2',
    name: 'Siti Nurhaliza W.',
    role: 'UI/UX Designer',
    company: 'Superteam MY',
    skills: ['Design', 'Content'],
    twitter: 'sitindesign',
    badge: 'Solana Builder',
    bio: 'Crafting Web3 experiences that feel human.',
    achievements: { hackathon_wins: 1, projects_built: 3, grants_received: 1, bounties_completed: 8 },
    featured: true,
  },
  {
    id: '3',
    name: 'James Tan',
    role: 'Growth Lead',
    company: 'Jupiter',
    skills: ['Growth', 'Community'],
    twitter: 'jamestan_sol',
    badge: 'Hackathon Winner',
    bio: 'Community builder connecting Malaysian talent to Solana.',
    achievements: { hackathon_wins: 2, projects_built: 4, grants_received: 0, bounties_completed: 15 },
    featured: true,
  },
  {
    id: '4',
    name: 'Priya Sharma',
    role: 'Smart Contract Dev',
    company: 'Marinade Finance',
    skills: ['Rust', 'Backend'],
    twitter: 'priyasol',
    badge: 'Core Contributor',
    bio: 'Securing DeFi protocols one audit at a time.',
    achievements: { hackathon_wins: 4, projects_built: 7, grants_received: 3, bounties_completed: 20 },
    featured: true,
  },
  {
    id: '5',
    name: 'Wei Lin',
    role: 'Founder',
    company: 'SolPay MY',
    skills: ['Product', 'Growth'],
    twitter: 'weilin_sol',
    badge: 'Grant Recipient',
    bio: 'Bringing Solana payments to Southeast Asian merchants.',
    achievements: { hackathon_wins: 2, projects_built: 2, grants_received: 2, bounties_completed: 5 },
    featured: true,
  },
  {
    id: '6',
    name: 'Amir Hassan',
    role: 'Full Stack Developer',
    company: 'Helius',
    skills: ['Frontend', 'Backend', 'Rust'],
    twitter: 'amirdev',
    badge: 'Hackathon Winner',
    bio: '3x hackathon winner. Currently building RPC infrastructure.',
    achievements: { hackathon_wins: 3, projects_built: 6, grants_received: 1, bounties_completed: 18 },
    featured: true,
  },
  {
    id: '7',
    name: 'Nurul Ain',
    role: 'Content Strategist',
    company: 'Superteam MY',
    skills: ['Content', 'Community'],
    twitter: 'nurulain_web3',
    badge: 'Solana Builder',
    bio: 'Telling the story of Web3 in Malaysia.',
    achievements: { hackathon_wins: 0, projects_built: 2, grants_received: 0, bounties_completed: 10 },
    featured: false,
  },
  {
    id: '8',
    name: 'Raj Patel',
    role: 'Data Engineer',
    company: 'Tensor',
    skills: ['Backend', 'Data'],
    twitter: 'rajpatel_data',
    badge: 'Bounty Hunter',
    bio: 'NFT analytics and on-chain data pipelines.',
    achievements: { hackathon_wins: 1, projects_built: 3, grants_received: 1, bounties_completed: 25 },
    featured: false,
  },
  {
    id: '9',
    name: 'Farah Izzati',
    role: 'Product Designer',
    company: 'Magic Eden',
    skills: ['Design', 'Product'],
    twitter: 'farahux',
    badge: 'Solana Builder',
    bio: 'Designing marketplaces that millions use daily.',
    achievements: { hackathon_wins: 1, projects_built: 4, grants_received: 0, bounties_completed: 7 },
    featured: false,
  },
  {
    id: '10',
    name: 'Daniel Lim',
    role: 'DevOps Engineer',
    company: 'Orca',
    skills: ['DevOps', 'Backend'],
    twitter: 'daniellim_ops',
    badge: 'Core Contributor',
    bio: 'Keeping Solana validators running 24/7.',
    achievements: { hackathon_wins: 0, projects_built: 5, grants_received: 1, bounties_completed: 14 },
    featured: false,
  },
  {
    id: '11',
    name: 'Aisyah Rahman',
    role: 'Community Manager',
    company: 'Superteam MY',
    skills: ['Community', 'Growth', 'Content'],
    twitter: 'aisyah_web3',
    badge: 'Core Contributor',
    bio: "Growing Malaysia's largest Solana community.",
    achievements: { hackathon_wins: 0, projects_built: 1, grants_received: 0, bounties_completed: 6 },
    featured: false,
  },
  {
    id: '12',
    name: 'Kevin Ng',
    role: 'Blockchain Researcher',
    company: 'UKM',
    skills: ['Research', 'Rust'],
    twitter: 'kevinng_phd',
    badge: 'Grant Recipient',
    bio: 'Academic researcher bridging traditional finance and DeFi.',
    achievements: { hackathon_wins: 2, projects_built: 3, grants_received: 4, bounties_completed: 3 },
    featured: false,
  },
];

export const FALLBACK_PARTNERS = [
  { id: '1', name: 'Solana Foundation', tier: 'platinum', website: 'https://solana.org' },
  { id: '2', name: 'Jupiter', tier: 'platinum', website: 'https://jup.ag' },
  { id: '3', name: 'Marinade Finance', tier: 'gold', website: 'https://marinade.finance' },
  { id: '4', name: 'Helius', tier: 'gold', website: 'https://helius.dev' },
  { id: '5', name: 'Tensor', tier: 'gold', website: 'https://tensor.trade' },
  { id: '6', name: 'Magic Eden', tier: 'gold', website: 'https://magiceden.io' },
  { id: '7', name: 'Orca', tier: 'silver', website: 'https://orca.so' },
  { id: '8', name: 'Phantom', tier: 'silver', website: 'https://phantom.app' },
  { id: '9', name: 'Backpack', tier: 'silver', website: 'https://backpack.app' },
  { id: '10', name: 'Jito', tier: 'silver', website: 'https://jito.wtf' },
  { id: '11', name: 'Pyth Network', tier: 'silver', website: 'https://pyth.network' },
  { id: '12', name: 'Raydium', tier: 'silver', website: 'https://raydium.io' },
];

export const FALLBACK_TESTIMONIALS = [
  {
    id: '1',
    author: 'Wei Lin',
    role: 'Founder, SolPay MY',
    content:
      'Superteam Malaysia connected me with the right mentors and helped us secure our first Solana grant. This community is a cheat code for builders.',
    twitter: 'weilin_sol',
    featured: true,
  },
  {
    id: '2',
    author: 'Amir Hassan',
    role: 'Developer, Helius',
    content:
      "The hackathons organized by Superteam MY are world-class. I built my first dApp here and now I'm working full-time in Solana.",
    twitter: 'amirdev',
    featured: true,
  },
  {
    id: '3',
    author: 'Farah Izzati',
    role: 'Designer, Magic Eden',
    content:
      "As a designer, I felt welcomed from day one. The community doesn't just value code — they value great product thinking.",
    twitter: 'farahux',
    featured: true,
  },
  {
    id: '4',
    author: 'Raj Patel',
    role: 'Data Engineer, Tensor',
    content:
      'The bounty ecosystem through Superteam Earn changed my career. I went from side projects to full-time Web3 in 3 months.',
    twitter: 'rajpatel_data',
    featured: true,
  },
];

export const FALLBACK_FAQS = [
  {
    id: '1',
    question: 'What is Superteam Malaysia?',
    answer:
      'Superteam Malaysia is the local chapter of the global Superteam network, dedicated to empowering builders, creators, founders, and talent in the Solana ecosystem. We provide mentorship, events, grants, and community.',
    display_order: 1,
  },
  {
    id: '2',
    question: 'How do I join?',
    answer:
      "Join our Telegram or Discord community, attend events, and start contributing. There's no formal application — just show up and build! Everyone from developers to designers to content creators is welcome.",
    display_order: 2,
  },
  {
    id: '3',
    question: 'What opportunities are available?',
    answer:
      'We offer bounties, grants, hackathons, jobs, mentorship, and ecosystem connections through the Superteam Earn platform. There are opportunities across development, design, content, growth, and more.',
    display_order: 3,
  },
  {
    id: '4',
    question: 'How can projects collaborate with us?',
    answer:
      'Reach out via Twitter @SuperteamMY or Telegram. We welcome partnerships with Solana projects, local Web3 companies, educational institutions, and anyone building in the ecosystem.',
    display_order: 4,
  },
  {
    id: '5',
    question: 'Do I need to be a developer to join?',
    answer:
      'Not at all! We welcome designers, content creators, community managers, business developers, researchers, and anyone passionate about Web3. The Solana ecosystem needs all kinds of talent.',
    display_order: 5,
  },
];
